# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viajesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('comentario', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('hotel', models.CharField(max_length=50)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='viajesApp.Viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('detalle', models.TextField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='viajesApp.Destino')),
            ],
        ),
    ]
